version: '3.9'

services:
  app:
    image: my_app_image:latest  # Specify the image name and tag
    ports:
      - "5000:80"
    deploy:
      replicas: 3
    environment:
      - REDIS_URL=redis://redis:6379
      - POSTGRES_URL=postgres://user:password@postgres:5432/mydatabase
    depends_on:
      - redis
      - postgres
    volumes:
      - orders_data:/app/orders.csv

  test:
    image: my_test_image:latest  # Specify the image name and tag
    depends_on:
      - redis
      - postgres
    volumes:
      - orders_data:/app/orders.csv

  redis:
    image: redis:latest
    deploy:
      replicas: 1

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    deploy:
      replicas: 1

volumes:
  orders_data:
